# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-10a3fcf52b4b47d7afaf0b8125f6e82a
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
#      response-format: json_object
      max-retries: 2
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-10a3fcf52b4b47d7afaf0b8125f6e82a
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      max-retries: 2

# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: ai-zero-code-1330582711.cos.ap-guangzhou.myqcloud.com
    secretId: AKIDoSu8C4nRsoXD9zfAUffU8btzvgHf098w
    secretKey: e7RaXKArUBitwmRyIVaX8YkjX8A4npgO
    region: ap-guangzhou
    bucket: ai-zero-code-1330582711

# Pexels 图片搜索配置
pexels:
  api-key: a7n1zMEu4dccQFxGpCv8pmuNjHSL4QspCE8rSCraXcuEa0CqQKm3FjbN

# 阿里云 DashScope 配置
dashscope:
  api-key: sk-275aa77f2beb4abcb5e09b25201eea86
  image-model: wan2.2-t2i-flash



